databases:
  - name: test_render
    databaseName: test_render_cbm5
    user: test_render_cbm5_user

services:
  - type: web
    name: test_render
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: test_render
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
